### ISSUE TITLE
ArrayIndexOutOfBounds in SimplifiedSchematic#rotate

### ISSUE THREAD

**Issue by RoboMWM** [kuohsuanlo/CyberWorld#2]
Unsure if me using FAWE affects this. I'll try on a server without it later.

```
[20:13:21] [Server thread/INFO]: RoboMWM issued server command: /mv create cyberworld2 normal -g CyberWorld
[20:13:21] [Server thread/INFO]: RoboMWM: Starting creation of world 'cyberworld2'...
[20:13:21] [Server thread/INFO]: [Multiverse-Core] Loading World & Settings - 'cyberworld2' - Env: NORMAL - Type: NORMAL & generator: CyberWorld
[20:13:21] [Server thread/WARN]: net.minecraft.server.v1_12_R1.ReportedException: Exception generating new chunk
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:958)
[20:13:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.createWorld(CraftServer.java:968)
[20:13:21] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:488)
[20:13:21] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[20:13:21] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466)
[20:13:21] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:268)
[20:13:21] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
[20:13:21] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[20:13:21] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[20:13:21] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[20:13:21] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:919)
[20:13:21] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[20:13:21] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[20:13:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472)
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277)
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[20:13:21] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:13:21] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[20:13:21] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[20:13:21] [Server thread/WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException: 7
[20:13:21] [Server thread/WARN]: 	at io.github.kuohsuanlo.cyberworld.SimplifiedSchematic.rotate(SimplifiedSchematic.java:84)
[20:13:21] [Server thread/WARN]: 	at io.github.kuohsuanlo.cyberworld.CyberWorldObjectGenerator.generateGroundDecoration(CyberWorldObjectGenerator.java:2044)
[20:13:21] [Server thread/WARN]: 	at io.github.kuohsuanlo.cyberworld.CyberWorldChunkGenerator.generateChunkData(CyberWorldChunkGenerator.java:43)
[20:13:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:52)
[20:13:21] [Server thread/WARN]: 	at co.aikar.timings.TimedChunkGenerator.getOrCreateChunk(TimedChunkGenerator.java:93)
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:194)
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:174)
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[20:13:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.loadChunk(CraftWorld.java:316)
[20:13:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.loadChunk(CraftWorld.java:205)
[20:13:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getHighestBlockYAt(CraftWorld.java:127)
[20:13:21] [Server thread/WARN]: 	at org.bukkit.generator.ChunkGenerator.canSpawn(ChunkGenerator.java:270)
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.WorldServer.canSpawn(WorldServer.java:269)
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.WorldServer.b(WorldServer.java:1021)
[20:13:21] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:943)
[20:13:21] [Server thread/WARN]: 	... 26 more
[20:13:21] [Server thread/ERROR]: [Multiverse-Core] The world 'cyberworld2' could NOT be loaded because it contains errors and is probably corrupt!
[20:13:21] [Server thread/ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'cyberworld2'
[20:13:21] [Server thread/ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
[20:13:21] [Server thread/ERROR]: [Multiverse-Core] Failed to Create/Load the world 'cyberworld2'
```

**Comment by RoboMWM** [comment]
Just ran this on a test server without FAWE, though I also used the version of CyberWorld uploaded in the target directory (since I was trying to get it to work without multiverse - was attempting to use worlds section in bukkit.yml to specify generator), so unsure which was at fault.

**Comment by kuohsuanlo** [comment]
I personally didn't try that before. But it should work in theory. The world generator name is `CyberWorld`.
